# Generated by Django 5.2.8 on 2025-11-23 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='text_background',
            field=models.CharField(blank=True, default='white', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='text_color',
            field=models.CharField(blank=True, default='black', max_length=50),
        ),
    ]
